modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="crits_bambood"
version="0.0.4"
displayName="Crit's Bamboo'd"
displayURL="https://modrinth.com/organization/silly-willies"
logoFile="logo.png"
credits="Made by Silly Willies org"
authors="Crit, Zomagon, P"
description="This mod is bamboo centered, with items like the Bamboo staff, different bamboo foods, and many more to come"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.crits_bambood]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.crits_bambood]]
modId="silly_willy_core"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.crits_bambood]]
modId="pehkui"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.crits_bambood]]
modId="use_compiled_mods"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.crits_bambood]]
modId="additions"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.crits_bambood]]
modId="geckolib"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.crits_bambood]]
modId="jei"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.crits_bambood]]
modId="silly_willy_core"
mandatory=true
versionRange="[0.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.crits_bambood]]
modId="geckolib"
mandatory=true
versionRange="[4.4.9,)"
ordering="AFTER"
side="BOTH"

# End of user code block dependencies configuration
